"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { FolderOpen, ImagePlus, LoaderCircle, MoreHorizontal, Trash2, Upload, ZoomIn, ZoomOut } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import PhotoModel from "./PhotoModel";
import {useWorkspaceState,useWorkspaceControls,undoWorkspace,redoWorkspace} from "./workspace-state";
import {ExportDestination} from "./export-destination";

export type StoredImage = { key:string; name:string; size:number; uploadedAt:string; folder?:"existing"|"new" };
const formatBytes=(bytes:number)=>bytes<1024?`${bytes} B`:bytes<1048576?`${Math.round(bytes/1024)} KB`:`${(bytes/1048576).toFixed(1)} MB`;

export default function Home(){
  const [images,setImages]=useState<StoredImage[]>([]),[loading,setLoading]=useState(true),[uploading,setUploading]=useState(false),[error,setError]=useState(""),[selectedIndex,setSelectedIndex]=useWorkspaceState("Home.selectedIndex",0),[positions,setPositions]=useWorkspaceState("Home.positions",{storage:{x:50,y:120},model:{x:760,y:120}}),[scale,setScale]=useWorkspaceState("Home.scale",1);
  const [activeFolder,setActiveFolder]=useWorkspaceState<"existing"|"new">("Home.activeFolder","existing");
  const folderImages=images.filter(image=>(image.folder||"existing")===activeFolder);
  const drag=useRef<{node:"storage"|"model";dx:number;dy:number}|null>(null),input=useRef<HTMLInputElement>(null),canvasRef=useRef<HTMLElement>(null);
  useWorkspaceControls(canvasRef);
  const loadImages=useCallback(async()=>{try{const r=await fetch("/api/images",{cache:"no-store"});if(!r.ok)throw new Error("Could not load your image folder.");const next=(await r.json()).images as StoredImage[];setImages(next);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load your image folder.")}finally{setLoading(false)}},[]);
  useEffect(()=>{void loadImages()},[loadImages]);
  useEffect(()=>{const move=(e:PointerEvent)=>{const rect=canvasRef.current?.getBoundingClientRect();if(drag.current&&rect){const node=drag.current.node;setPositions(p=>({...p,[node]:{x:Math.max(12,e.clientX-rect.left+(canvasRef.current?.scrollLeft||0)-drag.current!.dx),y:Math.max(20,e.clientY-rect.top+(canvasRef.current?.scrollTop||0)-drag.current!.dy)}}))}};const up=()=>{drag.current=null};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up);return()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)}},[]);
  const startDrag=(node:"storage"|"model")=>(e:React.PointerEvent)=>{if(e.button!==0||(e.target as HTMLElement).closest("button"))return;const rect=canvasRef.current?.getBoundingClientRect();if(!rect)return;drag.current={node,dx:e.clientX-rect.left+(canvasRef.current?.scrollLeft||0)-positions[node].x,dy:e.clientY-rect.top+(canvasRef.current?.scrollTop||0)-positions[node].y}};
  async function uploadFiles(files:FileList|File[]){const accepted=Array.from(files).filter(f=>f.type.startsWith("image/"));if(!accepted.length)return;setUploading(true);setError("");try{for(const file of accepted){const form=new FormData();form.append("image",file);form.append("folder",activeFolder);const r=await fetch("/api/images",{method:"POST",body:form});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error||`Could not upload ${file.name}.`)}}await loadImages()}catch(e){setError(e instanceof Error?e.message:"The upload did not finish.")}finally{setUploading(false);if(input.current)input.current.value=""}}
  async function removeImage(key:string){const old=images;setImages(v=>v.filter(i=>i.key!==key));const r=await fetch("/api/images",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({key})});if(!r.ok){setImages(old);setError("That image could not be removed.")}else setSelectedIndex(0)}
  const selected=folderImages[Math.min(selectedIndex,Math.max(0,folderImages.length-1))];
  return <main className="board-shell"><header className="topbar"><div className="brand-mark">SS</div><div><h1>Sand Scan</h1><p>Depth-to-volume studio</p></div><div className="topbar-actions"><ExportDestination/><button className="history-button" onClick={undoWorkspace} title="Undo (Ctrl+Z)">Undo</button><button className="history-button" onClick={redoWorkspace} title="Redo (Ctrl+Alt+Z)">Redo</button><span className="saved-state"><i/>Settings remembered</span><Button variant="outline" size="icon" aria-label="More board options"><MoreHorizontal/></Button></div></header>
    <section ref={canvasRef} className="canvas" aria-label="Workflow whiteboard"><div className="canvas-hint">Middle-mouse drag to pan · Ctrl+Z undo · Ctrl+Alt+Z redo</div><div className="workflow-extent" aria-hidden="true"/>
      <svg className="wire-layer" aria-hidden="true"><path d={`M ${positions.storage.x+540} ${positions.storage.y+300} C ${positions.storage.x+620} ${positions.storage.y+300}, ${positions.model.x-80} ${positions.model.y+250}, ${positions.model.x} ${positions.model.y+250}`}/></svg>
      <article data-node="storage" className="storage-node" style={{left:positions.storage.x,top:positions.storage.y,transform:`scale(${scale})`,transformOrigin:"top left"}}><header className="node-header" onPointerDown={startDrag("storage")}><div className="folder-icon"><FolderOpen/></div><div><h2>Image Storage</h2><p>{images.length} {images.length===1?"image":"images"} saved</p></div><span className="drag-label">DRAG</span></header><div className="node-body"><div className="storage-folders" role="group" aria-label="Image folders">{([{id:"existing",name:"Model Photos"},{id:"new",name:"Midjourney Photos"}] as const).map(folder=><button key={folder.id} aria-pressed={activeFolder===folder.id} onClick={()=>{setActiveFolder(folder.id);setSelectedIndex(0)}} disabled={uploading}><FolderOpen size={20}/><strong>{folder.name}</strong><span>{images.filter(image=>(image.folder||"existing")===folder.id).length} photos</span></button>)}</div><input ref={input} type="file" accept="image/*" multiple hidden onChange={e=>e.target.files&&void uploadFiles(e.target.files)}/><button className="dropzone" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void uploadFiles(e.dataTransfer.files)}} disabled={uploading}>{uploading?<LoaderCircle className="spin"/>:<ImagePlus/>}<strong>{uploading?"Adding images…":"Import images"}</strong><span>Choose files or drop them here</span></button>{error&&<p className="error" role="alert">{error}</p>}
        <div className="image-grid">{loading?Array.from({length:3}).map((_,i)=><div className="image-skeleton" key={i}/>):folderImages.map((image,i)=><figure className={`image-card ${i===selectedIndex?"selected":""}`} key={image.key} onClick={()=>setSelectedIndex(i)}><img src={`/api/images/content?key=${encodeURIComponent(image.key)}`} alt={image.name}/><figcaption><div><strong title={image.name}>{image.name}</strong><span>{formatBytes(image.size)}</span></div><button aria-label={`Remove ${image.name}`} onClick={e=>{e.stopPropagation();void removeImage(image.key)}}><Trash2/></button></figcaption></figure>)}</div>{!loading&&!folderImages.length&&<div className="empty-note"><Upload/>This folder is empty. Import photos to get started.</div>}
        {!!folderImages.length&&<div className="selector"><div className="selector-label"><span>Image to analyze</span><strong>{Math.min(selectedIndex,folderImages.length-1)+1} / {folderImages.length}</strong></div><Slider min={0} max={Math.max(0,folderImages.length-1)} step={1} value={[Math.min(selectedIndex,Math.max(0,folderImages.length-1))]} onValueChange={value=>setSelectedIndex(value[0]??0)} aria-label="Select image to analyze"/><div className="selected-file"><img src={`/api/images/content?key=${encodeURIComponent(selected.key)}`} alt=""/><span>{selected.name}</span></div></div>}
        </div><span className="port port-left"/><span className="port port-right" aria-hidden="true"/></article>
      {!loading&&<PhotoModel images={images} position={positions.model} onDragStart={startDrag("model")}/>}<div className="zoom-controls"><button onClick={()=>setScale(v=>Math.max(.75,v-.1))} aria-label="Zoom out"><ZoomOut/></button><span>{Math.round(scale*100)}%</span><button onClick={()=>setScale(v=>Math.min(1.2,v+.1))} aria-label="Zoom in"><ZoomIn/></button></div>
    </section></main>
}
